--1
--C
CREATE TABLE MYST_MAJOR_CITIES(
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM ST_POINT
);

--D
INSERT INTO MYST_MAJOR_CITIES
SELECT
    FIPS_CNTRY,
    CITY_NAME,
    ST_POINT(GEOM)
FROM MAJOR_CITIES;

--2
--A

INSERT INTO MYST_MAJOR_CITIES
VALUES('PL', 'SZCZYRK', TREAT(ST_Point.from_wkt('POINT(19.036107 49.718655)',8307) AS ST_POINT));

--B
SELECT
    name,
    ST_POINT(GEOM).GET_WKT()
FROM rivers;
    
--C
SELECT 
    SDO_UTIL.TO_GMLGEOMETRY(ST_POINT.GET_SDO_GEOM(STGEOM))
FROM MYST_MAJOR_CITIES
WHERE city_name = 'SZCZYRK';

--3
--A
create table MYST_COUNTRY_BOUNDARIES (
    FIPS_CNTRY VARCHAR2(2),
    CNTRY_NAME VARCHAR2(40),
    STGEOM ST_MULTIPOLYGON);

--B
insert into MYST_COUNTRY_BOUNDARIES
select B.FIPS_CNTRY, B.CNTRY_NAME, ST_MULTIPOLYGON(B.GEOM)
from COUNTRY_BOUNDARIES B;

--C
select 
    B.STGEOM.ST_GEOMETRYTYPE() TYP_OBIEKTU, 
    COUNT(*) AS ILE
from   MYST_COUNTRY_BOUNDARIES B
GROUP BY  B.STGEOM.ST_GEOMETRYTYPE();

--D
select 
    B.STGEOM.ST_ISSIMPLE()
from   MYST_COUNTRY_BOUNDARIES B;

--4
--A
select B.CNTRY_NAME, count(*)
from
MYST_COUNTRY_BOUNDARIES B,
MYST_MAJOR_CITIES C
where C.STGEOM.ST_WITHIN(B.STGEOM) = 1
group by B.CNTRY_NAME;

--B
select A.CNTRY_NAME A_NAME, B.CNTRY_NAME B_NAME
from
    MYST_COUNTRY_BOUNDARIES A,
    MYST_COUNTRY_BOUNDARIES B
where A.STGEOM.ST_TOUCHES(B.STGEOM) = 1
and B.CNTRY_NAME = 'Czech Republic';

--C
SELECT distinct B.CNTRY_NAME, R.name
FROM MYST_COUNTRY_BOUNDARIES B, RIVERS R
WHERE B.CNTRY_NAME = 'Czech Republic'
AND ST_LINESTRING(R.GEOM).ST_INTERSECTS(B.STGEOM) = 1;

--D
select round(TREAT(A.STGEOM.ST_UNION(B.STGEOM) as ST_POLYGON).ST_AREA(),-2) AS powierzchnia
from MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
where A.CNTRY_NAME = 'Czech Republic'
and B.CNTRY_NAME = 'Slovakia';

--E
select 
    TREAT(B.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(W.GEOM)) as ST_POLYGON).ST_GEOMETRYTYPE() 
from
MYST_COUNTRY_BOUNDARIES B, WATER_BODIES W
where B.CNTRY_NAME = 'Hungary'
and
W.name = 'Balaton';

