--1
--A
CREATE TABLE A6_LRS
(
    GEOM SDO_GEOMETRY
);

--B
INSERT INTO A6_LRS
SELECT S.GEOM
FROM STREETS_AND_RAILROADS S, MAJOR_CITIES C 
WHERE SDO_WITHIN_DISTANCE(C.GEOM, S.GEOM, 'distance=10 unit=km') = 'TRUE' 
AND C.CITY_NAME= 'Koszalin';

--C
SELECT
    SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km') DISTANCE,
    ST_LINESTRING(GEOM) .ST_NUMPOINTS() ST_NUMPOINTS
FROM A6_LRS;

--D
UPDATE A6_LRS
SET GEOM = (SELECT SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, 276.681) FROM A6_LRS WHERE 1=1)
WHERE 1=1;

--E
INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('A6_LRS','GEOM',
MDSYS.SDO_DIM_ARRAY(
 MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
 MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
 MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1) ),
 8307);
 
 --F
 CREATE INDEX lrs_routes_idx ON A6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
 
 --2
 --A
SELECT 
    SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500
FROM A6_LRS;

--B
SELECT
    SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT
FROM A6_LRS;

--C
SELECT 
    SDO_LRS.GEOM_SEGMENT_END_PT(SDO_LRS.LOCATE_PT(GEOM, 150, 0)) KM150
FROM A6_LRS;

--D
SELECT 
    SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPED 
from A6_LRS;

--E
SELECT 
    SDO_LRS.GET_NEXT_SHAPE_PT(A6.GEOM, C.GEOM) WJAZD_NA_A6
FROM A6_LRS A6, MAJOR_CITIES C 
WHERE C.CITY_NAME = 'Slupsk';

--F
select  
 (SDO_GEOM.SDO_LENGTH(SDO_LRS.OFFSET_GEOM_SEGMENT(A6.GEOM, M.DIMINFO, 50, 200, 50,
 'unit=m'), 1, 'unit=km')) * 1000000 as Koszt
from A6_LRS A6, USER_SDO_GEOM_METADATA M
where M.TABLE_NAME = 'A6_LRS' and M.COLUMN_NAME = 'GEOM';
